# host: www.activesphere.com
excerpt_separator: "\n\n\n"
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
production: true
title: ActiveSphere - Bangalore based software consulting
category_dir: /blog/category
exclude:
- README.md
- Rakefile
- .gitignore

plugins:
- jekyll-sitemap
- jekyll-feed
