# host: www.activesphere.com
excerpt_separator: "\n\n\n"
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
production: true
title: ActiveSphere - Bangalore based software consulting
category_dir: /blog/category
exclude:
  - README.md
  - Rakefile
  - .gitignore
  - webpack.config.js
  - .editorconfig
  - .babelrc
  - node_modules

plugins:
  - jekyll-sitemap
  - jekyll-feed

keep_files:
  - public/main.js
  - public/main.css


categories:
  posts:
    layout_modifier: article

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      content_containers: article
