destination: ./_site2
host: blog.activesphere.com
permalink: /blog/:year/:month/:day/:title
pygments: true
production: true
title: ActiveSphere - India based Ruby Rails JavaScript consulting
category_dir: /blog/category
exclude:
- README.md
- Rakefile
- .gitignore
